### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by 153957** [HiSPARC/firmware#2]
Fix docs;
- [x] quantization error is in nanoseconds
- [x] highest bit of CTP is synchronization bit, remove when using CTP as CTP..
- [ ] ~~add note about 1 second offset in HiSPARC timestamps..~~
- [x] Clarify order of PPS/Primary timing/OSM/timestamps
- [x] thresholds are in ADC counts. i.e. 0x100 will trigger at 256 ADC counts, so the pulseheight will be 56 ADC counts if the baseline is 200 counts.

**Comment by davidfokkema** [comment]
Added note about the thresholds, which are incorrectly described in the document.

**Comment by davidfokkema** [comment]
WE FOUND IT!

There is a delay between the GPS PPS and the GPS Primary Timing Packet of up to 20 ms, according to the Trimble docs. This means that the HiSPARC module can't be sure of the exact GPS time unless it keeps track of time itself. In that case, it would need to increment the clock with one second whenever it receives the PPS, but it should tick over seconds, minutes, hours, days, etc. when needed. It doesn't do that. When it receives a PrimaryTimingPacket, the HiSPARC hardware sets it apart and does _not_ update the clock. Only when it receives the next PPS, it shifts in the now _old_ PrimaryTimingPacket, sends it to the software and uses that clock time to use for event messages. That means that the HiSPARC clock is _behind the GPS clock by exactly one second!_ The hardware relies on the software to rectify that.

**Comment by 153957** [comment]
Fixed in 37b0bb420411d9403c5c0205f5afd088e20e6dd5
